### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by benfreking123** [magemonkeystudio/fabled#1213]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [x] I have tested without OP

### Current Behavior

Currently the Buff Mechanic does not work as expect applying no change to damage.
```
Gattling:
  name: Gattling
  type: Projectile
  max-level: "20"
  skill-req-lvl: 0
  needs-permission: "true"
  cooldown-message: "true"
  msg: "&6{player} &2has cast &6{skill}"
  combo: ""
  icon: Crossbow
  icon-data: 0
  icon-lore:
    - "&d{name} &7({level}/{max})"
    - "&2Type: &6{type}(50%)"
    - "&2Tier: &7Common"
    - "&7Shoots a small projectile"
    - ""
    - "{req:level}Level: {attr:level}"
    - "{req:cost}Cost: {attr:cost}"
    - ""
    - "&2Damage: {attr:Damage.value}"
    - "&2Mana: {attr:mana}"
    - "&2Cooldown: {attr:cooldown}"
  attributes:
    level-base: "1"
    level-scale: "0"
    cost-base: "1"
    cost-scale: "0"
    cooldown-base: "2.25"
    cooldown-scale: "-0.1"
    mana-base: "2"
    mana-scale: "1"
    points-spent-req-base: "0"
    points-spent-req-scale: "0"
  incompatible: []
  components:
    Cast:
      type: trigger
      comment: ""
      children:
        Particle Projectile:
          type: mechanic
          comment: ""
          preview:
            enabled: "false"
            period: "5"
            per-target: false
            path: false
          data:
            icon-key: ""
            counts: "true"
            pierce: false
            group: Enemy
            steps: "2"
            collision-radius-base: "0.5"
            collision-radius-scale: "0"
            gravity-base: "-0.04"
            gravity-scale: "0"
            drag-base: "0.02"
            drag-scale: "0"
            period: "2"
            homing: false
            velocity-base: "3"
            velocity-scale: "0"
            lifespan-base: "2"
            lifespan-scale: "0"
            distance-base: "10"
            distance-scale: "0"
            on-expire: false
            spread: Cone
            amount-base: "1"
            amount-scale: "0"
            angle-base: "30"
            angle-scale: "0"
            forward-base: "0"
            forward-scale: "0"
            upward-base: "0"
            upward-scale: "0"
            right-base: "0"
            right-scale: "0"
            particle: Crit
            arrangement: Sphere
            radius-base: "0.01"
            radius-scale: "0"
            particles-base: "1"
            particles-scale: "0"
            visible-radius: "25"
            dx: "0"
            dy: "0"
            dz: "0"
            amount: "1"
            speed: "0.1"
            use-effect: false
          children:
            Buff:
              type: mechanic
              comment: ""
              data:
                icon-key: ""
                counts: false
                immediate: true
                modifier: Multiplier
                value-base: "120"
                value-scale: 0
            Damage:
              type: mechanic
              comment: ""
              data:
                icon-key: Damage
                counts: "true"
                type: Damage
                value-base: "5"
                value-scale: "0.5"
                "true": false
                classifier: DIVINITY_projectile
                knockback: false
                ignore-divinity: false
                cause: Custom
            Particle:
              type: mechanic
              comment: ""
              data:
                icon-key: ""
                counts: "true"
                particle: Damage indicator
                arrangement: Sphere
                radius-base: "0.1"
                radius-scale: "0"
                particles-base: "1"
                particles-scale: "0"
                visible-radius: "25"
                dx: "0"
                dy: "0"
                dz: "0"
                amount: "1"
                speed: "0"
                forward: "0"
                upward: "3"
                right: "0"

`

### Expected Behavior

Expect a change in the Damage Mechanic after the Buff Mechanic is Applied

### Steps To Reproduce

Download Spell "Gattling"
Observer Structure to confirm configuration is correct
Cast Spell to see damage is not effected when editing the Buff Mechanic in the "Gattling" yml
-
To Reproduce without Download of Gattling:
Create New Spell
Add Cast as Main Trigger
Add Any Targeting
Add Mechanic Buff - with either Immediate = True or using DIVINITY_<damagetype>, neither one works
Add Damage Mechanic

### Environment

```markdown
- Server Software: Paper 1.21.4-207
- Fabled Version: 1.0.4-R0.41
- Codex Version: 1.1.0-R0.18
- Plugins: ALOT... This shouldn't be involved, can get if needed
```

### latest.log

No Error on the Server, When Casting, Loading, Damaging or anything.
